// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musicana.Api.Data;

#nullable disable

namespace Musicana.Api.Migrations
{
    [DbContext(typeof(MusicanaDbContext))]
    partial class MusicanaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Musicana.Api.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            ImageUrl = "/Instruments/Guitar.jpg",
                            IsDeleted = false,
                            Name = "Guitar",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            ImageUrl = "/Instruments/piano.jpg",
                            IsDeleted = false,
                            Name = "Piano",
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            ImageUrl = "/Instruments/piano.jpg",
                            IsDeleted = false,
                            Name = "Piano",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            ImageUrl = "/Instruments/piano.jpg",
                            IsDeleted = false,
                            Name = "Piano",
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            ImageUrl = "/Instruments/piano.jpg",
                            IsDeleted = false,
                            Name = "Piano",
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description 6",
                            ImageUrl = "/Instruments/Guitar.jpg",
                            IsDeleted = false,
                            Name = "Guitar",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Genre")
                        .HasMaxLength(60)
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Musicians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 6,
                            IsDeleted = false,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 0,
                            IsDeleted = false,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1985, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 5,
                            IsDeleted = false,
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1988, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 4,
                            IsDeleted = false,
                            Name = "Alice Brown"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1995, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 1,
                            IsDeleted = false,
                            Name = "Charlie Davis"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1991, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 3,
                            IsDeleted = false,
                            Name = "Emily Wilson"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1987, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 2,
                            IsDeleted = false,
                            Name = "Michael Taylor"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1993, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = 0,
                            IsDeleted = false,
                            Name = "Sarah Miller"
                        });
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician_Instrument", b =>
                {
                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.HasKey("MusicianId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Musician_Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            MusicianId = 1,
                            InstrumentId = 1
                        },
                        new
                        {
                            MusicianId = 2,
                            InstrumentId = 2
                        },
                        new
                        {
                            MusicianId = 3,
                            InstrumentId = 3
                        },
                        new
                        {
                            MusicianId = 4,
                            InstrumentId = 4
                        },
                        new
                        {
                            MusicianId = 1,
                            InstrumentId = 2
                        },
                        new
                        {
                            MusicianId = 2,
                            InstrumentId = 3
                        },
                        new
                        {
                            MusicianId = 3,
                            InstrumentId = 4
                        },
                        new
                        {
                            MusicianId = 4,
                            InstrumentId = 1
                        });
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician_Song", b =>
                {
                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("MusicianId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("Musician_Songs", (string)null);

                    b.HasData(
                        new
                        {
                            MusicianId = 1,
                            SongId = 1
                        },
                        new
                        {
                            MusicianId = 2,
                            SongId = 2
                        },
                        new
                        {
                            MusicianId = 3,
                            SongId = 3
                        },
                        new
                        {
                            MusicianId = 4,
                            SongId = 4
                        },
                        new
                        {
                            MusicianId = 1,
                            SongId = 2
                        },
                        new
                        {
                            MusicianId = 2,
                            SongId = 3
                        },
                        new
                        {
                            MusicianId = 3,
                            SongId = 4
                        },
                        new
                        {
                            MusicianId = 4,
                            SongId = 1
                        });
                });

            modelBuilder.Entity("Musicana.Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PlayCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 1",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 1,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 1"
                        },
                        new
                        {
                            Id = 2,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 2",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 0,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 2"
                        },
                        new
                        {
                            Id = 3,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 3",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 6,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 3"
                        },
                        new
                        {
                            Id = 4,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 4",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 4,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 4"
                        },
                        new
                        {
                            Id = 5,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 5",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 3,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 5"
                        },
                        new
                        {
                            Id = 6,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 6",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 1,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 6"
                        },
                        new
                        {
                            Id = 7,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 7",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 4,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 7"
                        },
                        new
                        {
                            Id = 8,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 8",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 2,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 8"
                        },
                        new
                        {
                            Id = 9,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 9",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 5,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 9"
                        },
                        new
                        {
                            Id = 10,
                            CoverImagePath = "/CoverImages/cover1.jpg",
                            Description = "Description 10",
                            Duration = 0.0,
                            FilePath = "/Songs/song1.mp3",
                            Genre = 1,
                            IsDeleted = false,
                            PlayCount = 0,
                            Title = "Song 10"
                        });
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician_Instrument", b =>
                {
                    b.HasOne("Musicana.Api.Models.Instrument", "Instrument")
                        .WithMany("musician_Instruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Musicana.Api.Models.Musician", "Musician")
                        .WithMany("musician_Instruments")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician_Song", b =>
                {
                    b.HasOne("Musicana.Api.Models.Musician", "Musician")
                        .WithMany("musician_Songs")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musicana.Api.Models.Song", "Song")
                        .WithMany("musician_Songs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Musicana.Api.Models.Instrument", b =>
                {
                    b.Navigation("musician_Instruments");
                });

            modelBuilder.Entity("Musicana.Api.Models.Musician", b =>
                {
                    b.Navigation("musician_Instruments");

                    b.Navigation("musician_Songs");
                });

            modelBuilder.Entity("Musicana.Api.Models.Song", b =>
                {
                    b.Navigation("musician_Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
